# Generated by Django 5.0.6 on 2024-06-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_address',
            new_name='hospital',
        ),
    ]
