# Generated by Django 5.0.6 on 2024-06-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_appointment_end_time_appointment_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
